// <auto-generated />
namespace NetWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class IntialDBCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialDBCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202002081251575_IntialDBCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
